import { RegionConfig } from './index';

const US_STATES = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
  { code: 'DC', name: 'District of Columbia' },
];

export const usConfig: RegionConfig = {
  locale: 'en-US',
  regionName: 'United States',
  countryCode: 'US',
  
  property: {
    energyRatings: {
      enabled: false,
      label: 'Energy Rating',
      required: false,
      ratings: [
        { code: 'HERS_0_50', label: 'HERS 0-50', description: 'Very efficient' },
        { code: 'HERS_51_100', label: 'HERS 51-100', description: 'Standard new home' },
        { code: 'HERS_101_130', label: 'HERS 101-130', description: 'Typical existing home' },
        { code: 'HERS_131_PLUS', label: 'HERS 131+', description: 'Less efficient' },
        { code: 'NOT_RATED', label: 'Not Rated' },
      ],
    },
    measurements: {
      areaUnit: 'sqft',
      areaLabel: 'Square Feet',
      areaSymbol: 'sq ft',
      convertFromSqm: (sqm: number) => sqm * 10.7639,
      convertToSqm: (sqft: number) => sqft / 10.7639,
      landUnit: 'acres',
      landLabel: 'Acres',
      landSymbol: 'acres',
      convertFromAcres: (acres: number) => acres,
      convertToAcres: (value: number) => value,
    },
    buildingTypes: [
      { code: 'Detached', label: 'Single Family' },
      { code: 'Semi-Detached', label: 'Duplex' },
      { code: 'Townhouse', label: 'Townhouse' },
      { code: 'Condo', label: 'Condo' },
      { code: 'Commercial', label: 'Commercial' },
      { code: 'Land', label: 'Land' },
    ],
    floorNumberingOffset: 1,
  },
  
  address: {
    postalCodeLabel: 'ZIP Code',
    postalCodePlaceholder: '10001',
    postalCodePattern: /^\d{5}(-\d{4})?$/,
    postalCodeFormat: '10001 or 10001-1234',
    countyLabel: 'County',
    countyRequired: false,
    stateLabel: 'State',
    stateRequired: true,
    states: US_STATES,
  },
  
  financial: {
    currency: 'USD',
    currencySymbol: '$',
    currencyPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    tax: {
      vatRate: 0,
      vatLabel: 'Sales Tax',
      vatEnabled: false,
    },
  },
  
  dateTime: {
    dateFormat: 'MM/DD/YYYY',
    timeFormat: '12h',
    firstDayOfWeek: 0,
  },
  
  legal: {
    terminology: {
      solicitor: 'Attorney',
      conveyancing: 'Title Insurance',
      stampDuty: 'Transfer Tax',
      freehold: 'Fee Simple',
      leasehold: 'Leasehold',
      listingAgent: 'Listing Agent',
      buyersAgent: 'Buyer\'s Agent',
    },
    compliance: {
      gdprEnabled: false,
      ccpaEnabled: true,
      amlRequired: true,
      fairHousingRequired: true,
      dataRetentionDays: 2555,
    },
  },
};
